name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build Linux
      run: dotnet publish -r linux-x64 --no-restore
    - name: Build Windows
      run: dotnet publish -r win-x64 --no-restore
    - name: Build OSX
      run: dotnet publish -r osx-x64 --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
