name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Linux
      run: dotnet publish -r linux-x64
    - name: Build Windows
      run: dotnet publish -r win-x64
    - name: Build OSX
      run: dotnet publish -r osx-x64
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload Linux Build
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: Linux Build
        # A file, directory or wildcard pattern that describes what to upload
        path: bin/Debug/netcoreapp3.1/linux-x64/
    - name: Upload OSX Build
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: Linux Build
        # A file, directory or wildcard pattern that describes what to upload
        path: bin/Debug/netcoreapp3.1/osx-x64/
    - name: Upload Windows Build
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: Linux Build
        # A file, directory or wildcard pattern that describes what to upload
        path: bin/Debug/netcoreapp3.1/win-x64/
