name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build -c Release ./AngelDoc/AngelDoc.csproj
    - name: Test
      run: dotnet test --verbosity normal ./AngelDoc.Tests/AngelDoc.Tests.csproj
    - name: Upload Build
      uses: actions/upload-artifact@v2.1.4
      with:
        name: AngelDoc
        path: AngelDoc/bin/Release/netcoreapp3.1/
